### ISSUE TITLE
Value Propostition on the Front Page

### ISSUE THREAD

**Issue by harrygfox** [foundersandcoders/our-site#102]
I think, more so than the motto, more so even than the name of the company we need a clear, catchy and encouraging value proposition.

Something like (though not limited to, nor exhaustively):
_Build your digital product_
_Become a developer - apply for our free 8 week course_
_Hire a development team - we can make your idea reality_
etc etc.....

I remember the old worries about this given that we want 1 set of users to apply for the course while we want the other set of users to hire us. However, I don't see any serious problem with having two value propositions on the landing page - please say if you feel otherwise.

Pursuant to all of the above I want to point you towards [this tweet](https://twitter.com/UserOnboard/status/408372844876165120) which highlights the different angle from which we should be marketing ourselves

**Comment by izaakrogan** [comment]
I've kept things pretty clean. There is definitely scope for something nice on the landing page. Ideally we would have a video/photo. More thought needed here. Let's talk about it in the week.

**Comment by harrygfox** [comment]
Directors! @sofer @iteles can you offer any insights?

**Comment by iteles** [comment]
I absolutely agree that we need people to immediately know what we're about when they hit the homepage. I don't think 'A co-operative of developers in London' fully captures this and it certainly isn't a 'call to action' in any way, but I think the wider issue here is that we actually don't _know_ what the main things we stand for is (I would say the school - unreservedly - but as we become more developer heavy, those priorities and apparently becoming murkier), we don't _know_ what the main thing we want to sell is.
I think we now have a sales team working on this and from the speed of things, we should know in the next few days.

**Comment by izaakrogan** [comment]
I think we need a plan for the next 12 months. If we can agree on some medium term goals, we can probably better define F&C - and come up with a decent value proposition. Agenda for the next business meeting? Focus group to make proposition to wider community?

**Comment by sofer** [comment]
I am still waiting for somebody to come up with a strapline that hits me between the eyes. It probably sits somewhere in the spaces between "we do a great job" and "we love what we do" and "we care about your web app". And I agree that a plan will help us. Now is a good time to bash out a one-page draft. 

We have a potential focus group for the value proposition this evening. Perhaps we could make a stab at it then.

**Comment by izaakrogan** [comment]
I've put something on the homepage. Let me know what you think

**Comment by sofer** [comment]
@harrygfox website front page currently undergoing a revamp. Let us know what you think of the current vp.

**Comment by harrygfox** [comment]
@izaakrogan @sofer It's funny how we've come full circle with the VP! I've had a play around and I think the guide from landing page to application is really good. There's not too much to juggle at once and it's clear what we do and what we mean. 

What's the plan for those users looking to hire a team or get a product built? Or is that a much bigger conversation that I've missed?

**Comment by rebeccaradding** [comment]
@harrygfox @sofer is this thread still relevant?

**Comment by harrygfox** [comment]
I think it should be constantly relevant to whoever's in charge of these decisions now (always good to ensure you're advertising the right value accurately), but it's clear that a VP has been chosen and implemented for each various arm of the business so I'd say this thread is out of date enough to be closed @rebeccaradding
