### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by izaakrogan** [foundersandcoders/our-site#106]
So, I've got quite a nice image for the training page. What do people reckon, should we have something similar for training and about?

**Comment by iteles** [comment]
I like the photo you've used on the training page as a photo, but I think that if we were to get a good photo of non-F&C people in an actual workshop environment (with F&C folks clearly doing the 'teaching'), that might be more representative. It would still work well as part of a set of images throughout the page. As a side note, if we can get a few women in there, that might be a good thing :wink: 

From a UX perspective, my humble opinion is that we don't need a 'splash' style image on every page - it works well for the homepage, but if you're clicking around your objective is to get to specific information, not to have to scroll past a large image before you find what you're looking for.

**Comment by iteles** [comment]
:laughing: Just noticed my hot water bottle made a cameo appearance to the left of the photo :heart:

**Comment by izaakrogan** [comment]
I agree, the image isn't perfect. Maybe we should ask someone from the current cohort to take charge of our Instagram account

**Comment by izaakrogan** [comment]
Do think you'll need it for a while! :sunny:

**Comment by izaakrogan** [comment]
Good point about the splash image on every page!

**Comment by iteles** [comment]
Closing this as no longer relevant (we won't have a training page for now) and can be reopened at a later date. Linked to #243
