### ISSUE TITLE
Separate freelancers website? 

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/our-site#214]
It may make sense to create a separate site for the freelancers.

**Comment by Jbarget** [comment]
as opposed to having an "Our Work" section on the FAC website?

**Comment by sofer** [comment]
@Jbarget exactly. At this point, it is just a suggestion.

**Comment by sohilpandya** [comment]
@sofer @iteles This is what I was thinking for a simple site for freelancers. 

- splash image, about us, pricing table, case studies. One page. clean and simple. IMO. 
![screen shot 2016-03-03 at 15 14 48](https://cloud.githubusercontent.com/assets/2305591/13498703/f9e9277a-e152-11e5-99d2-a4c63780b490.png)
![screen shot 2016-03-03 at 15 13 40](https://cloud.githubusercontent.com/assets/2305591/13498704/f9e92f68-e152-11e5-9e9b-6a4487d0c171.png)

**Comment by sofer** [comment]
@sohilpandya I agree that it should be kept simple. You will also want case studies. Having a pricing table may be controversial, but otoh may help frame the conversation with prospective clients (*"A working prototype delivered in two weeks for £2,000. A fully-functional MVP delivered in one month for £5,000"*?).

**Comment by sohilpandya** [comment]
@sofer Yep, maybe use from £2000 to give an estimate.

**Comment by iteles** [comment]
@sohilpandya We have a F&C colour scheme? Grey? :sob:

**Comment by sohilpandya** [comment]
@iteles This is a really cool place to look for color schemes - http://www.lolcolors.com

maybe we pick one as our official colour scheme, or we could keep with the grayscale.
![screen shot 2016-03-03 at 21 32 39](https://cloud.githubusercontent.com/assets/2305591/13510215/7d42a036-e187-11e5-8619-2c161ed3f818.png)

**Comment by iteles** [comment]
Please let's step away from the ALL GREY. It makes it look like an unfinished wireframe.

**Comment by sohilpandya** [comment]
@iteles agreed. I'll create a demo one, which we can all look at and get feedback on, will post it on here soon. :four_leaf_clover:

**Comment by sohilpandya** [comment]
this is what I was thinking, forget the image/color shceme for now, just focus on the layout. 

- Header Spash
- About Us
- Pricing
- List of case Studies
- Footer
[parallax.html.zip](https://github.com/foundersandcoders/oursite/files/159112/parallax.html.zip)

**Comment by sofer** [comment]
This discussion has moved to https://github.com/foundersandcoders/business/issues/37

**Comment by rebeccaradding** [comment]
Closing, as this discussion moved elsewhere.
