### ISSUE TITLE
Next steps?

### ISSUE THREAD

**Issue by des-des** [foundersandcoders/our-site#236]
It has been said that the site needs some work.

I have gone and added labels priority 1-5 (but was not very inventive with the colours). I think a good place to start would be to put some priority flags some of the stuff on the backlog. Also if there is anything that needs doing not captured in an issue we need to make one. Then people who are intersted in helping can assign themselves issues :smile: 

1 - urgent (everything is broken)
2 - do this next
3 - etc ...

@sofer @rub1e ?

**Comment by iteles** [comment]
It may be bigger than this with the site needing a rethink of content as a whole, but good start 👍 

Also, swapped the label colours to standard dwyl colours for (my) ease 😉

**Comment by sofer** [comment]
@des-des @iteles I have added and labelled my priority issues plus opened a pr. I accept the opinion of @ronanyeah that a to-do list would be more useful at this point than a wholesale redesign.

**Comment by sofer** [comment]
[Current priorities](https://github.com/foundersandcoders/oursite/issues?q=is%3Aissue+is%3Aopen+label%3Apriority-1).
