### ISSUE TITLE
Site redesign

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/our-site#243]
I have asked @nogainbar to come up with some concepts for a new site. Watch this space.

**Comment by iteles** [comment]
Thanks @nogainbar! I imagine your first step is knowing what content should be on the site, so please let @sofer and I know if it would be useful for us to have a 20 minute brainstorm with you (for example) 😊

**Comment by sofer** [comment]
@nogainbar reprioritising to priority 1. Are you and anyone else who is interested available any time on Monday 3rd to discuss?

**Comment by nogainbar** [comment]
Yes! Totally up for it! Would be great to brainstorm with you and ines about this!

**Comment by iteles** [comment]
I'm only back on the 5th but could do a hangouts before that!

**Comment by sofer** [comment]
@iteles that's fantastic. I think it's likely to be around the middle of the day on Monday. I am available from 12. I have now stopped (or at least slowed down with) messing around with the existing website. The copy and navigation is close to where I want it to be.  The top level now looks like this:

||||||
|----|----|----|----|----|----|
|HOME|FOUNDERS|CODERS|COMMUNITY|OUR STORY|

The site now better reflects a pitch which I have been making and refining 3-4 times a day every day for the last week or so. It also better reflects the 30-sec video segments I have asked [Blake House](http://blake.house/) to make for us, so we can have a video to introduce every top level page--if we want it.

Having said that, I truly welcome input on the content--and particularly on the home page which I have hardly touched.

**Comment by sofer** [comment]
I believe @harrygfox and @rebeccaradding are joining us, too.

**Comment by sofer** [comment]
@iteles do you want us to push this session to Wednesday?

**Comment by iteles** [comment]
Would make sense 👍

**Comment by sofer** [comment]
OK. I've got Ieva from Blake House coming in on Monday. We can downgrade the meeting on Monday to be about use of video on the website and we can have a follow-up meeting on Wednesday. 

@nogainbar @harrygfox will you be able to join us on Wednesday?

@iteles please suggest a time.

**Comment by iteles** [comment]
Afternoon! 

@sofer I'm not sure how Ieva fits into the website redesign? 😊

**Comment by rebeccaradding** [comment]
Site has not been redesigned, but @jsms90 has significantly increased usability. Closing this issue for the time being.
