### ISSUE TITLE
Workshops section

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/our-site#245]
We need a top-level section describing our workshops, hackathons and design sprints

See https://goo.gl/photos/dumikSqrdzsKpVtX6

**Comment by des-des** [comment]
@sofer This is priority 2. Do we have any copy for this? Who has the knowledge to put something together?

**Comment by rebeccaradding** [comment]
@des-des I believe we decided not to include this information on the website and to instead focus our efforts on documenting the results of these events through case studies on the portfolio page.
