### ISSUE TITLE
Homepage updates

### ISSUE THREAD

**Issue by iteles** [foundersandcoders/our-site#273]
- [x] Add Founders & Coders logo to home screen #104 
- [x] Upload color still photo for home screen: https://drive.google.com/open?id=0BzAAKt4fbFbgd3BOT1o0UExUQm8
- [x] Lift grayscale filter from ALL photos on website if possible
- [x] Enlarge social media buttons if possible to make them more visible on the site.

<hr/>

This is part of a larger [content refactor](https://github.com/foundersandcoders/oursite/milestone/1), led by @rebeccaradding. I'm translating the [proposed content doc](https://docs.google.com/document/d/1a1QCi_9FhIB0HaVlIqsccM3EFDOvfoCuBuoPgb8rOs8/edit?usp=sharing) into issues so action can be taken.

**Comment by rebeccaradding** [comment]
@iteles checking to see if the home page photo is still being updated to a new color shot. The preview is showing the B&W. Thanks!

**Comment by des-des** [comment]
moving to priority 2 as only logo to go

**Comment by des-des** [comment]
@iteles Where do we want to put the logo

**Comment by njsfield** [comment]
@des-des are you working on the site logo issue? If not me and @skibinska will be happy to help?

**Comment by rebeccaradding** [comment]
All items done, closing issue.
