### ISSUE TITLE
"dwyl/cast/israel tech" bar in every page

### ISSUE THREAD

**Issue by franzmoro** [foundersandcoders/our-site#303]
Comments:
- Is this intended or should it go just on the "home" page?
- Logos are not clickable

**Comment by sofer** [comment]
@franzmoro we should make them clickable. 
http://www.dwyl.io/
http://www.wearecast.org.uk/
http://www.ukisraelhub.com/

**Comment by franzmoro** [comment]
@sofer ok for the links. Should these 3 logos still appear on every page? Potentially we could display them in selected pages (maybe it doesn't fit as nicely on the "portfolio" page?).

**Comment by sohilpandya** [comment]
Has this been completed? Can we close this issue?

**Comment by franzmoro** [comment]
@sohilpandya actually just the 2nd point has been addressed really...
I personally think that these 3 links should not be appearing everywhere but (maybe) just in the home page. Don't know if anyone else has an opinion(?).

**Comment by iteles** [comment]
@sofer put them on originally, reckon we should get his thoughts on it 👍

**Comment by rebeccaradding** [comment]
Closing, as logos now appear only on location-specific pages, for reasons related to sensitivity around FAC Gaza/FAC Nazareth.
