### ISSUE TITLE
HTTPS connections should be allowed.

### ISSUE THREAD

**Issue by ronanyeah** [foundersandcoders/our-site#336]
What's the situation with HTTPS certs? Do they need to be updated on github pages or something?

**Comment by ronanyeah** [comment]
https://help.github.com/articles/securing-your-github-pages-site-with-https/

**Comment by ronanyeah** [comment]
https://www.reddit.com/r/github/comments/4vk76l/chrome_warning_about_githubpages_sites_not_being/

**Comment by iteles** [comment]
@ronanyeah Is https://github.com/foundersandcoders/oursite/pull/337 linked to this?

**Comment by ronanyeah** [comment]
I don't think so unfortunately. The warning is something like 'www.foundersandcoders.com is using a certificate from github.com'.

**Comment by ronanyeah** [comment]
@iteles also claire just showed me this, is this the process for FAC repos as well, and if so should it be added to the README/contrib guide of this repo?
https://github.com/dwyl/contributing/issues/28

**Comment by iteles** [comment]
@ronanyeah I would love it to be, but I won't be the one enforcing it so it's not my call :blush:

**Comment by iteles** [comment]
(I love that Claire found that :laughing: :heart;)

**Comment by sofer** [comment]
@ronanyeah #337 merged and published. Thanks. 

@iteles a sweepstake on when we get round to it?

**Comment by ronanyeah** [comment]
basically https is unavailable because we have a custom domain set up. it is still possible to get around this however. is there a fac cloudflare account?
https://sheharyar.me/blog/free-ssl-for-github-pages-with-custom-domains/

**Comment by ronanyeah** [comment]
Done!
