### ISSUE TITLE
Google search results 

### ISSUE THREAD

**Issue by rebeccaradding** [foundersandcoders/our-site#338]
When you search for "Founders & Coders," this is what displays - notice that the website pages it references are outdated. 

![screen shot 2016-11-05 at 2 03 16 pm](https://cloud.githubusercontent.com/assets/21280084/20030612/afeadb02-a360-11e6-9a44-72f46bf349fc.png)

**Comment by sofer** [comment]
Those result will take a while to shake out. They already have in the UK (at least for me).

**Comment by iteles** [comment]
https://support.google.com/sites/answer/100283?hl=en

**Comment by iteles** [comment]
@rebeccaradding How's it looking for you now?

For me it's this and HIRE US goes straight to a 404 page:
<img width="601" alt="screen shot 2016-12-03 at 19 49 21" src="https://cloud.githubusercontent.com/assets/4185328/20861831/a2ecf358-b991-11e6-9f71-d09a850068c4.png">

**Comment by rebeccaradding** [comment]
@iteles when I search now, it comes up with:
![screen shot 2016-12-03 at 7 56 21 pm](https://cloud.githubusercontent.com/assets/21280084/20861870/9778f9ee-b992-11e6-9ebb-2c96efcd67bc.png)

**Comment by kelsh** [comment]
This is the way we do it at my work:

https://support.google.com/webmasters/answer/183669?hl=en
