### ISSUE TITLE
Update Apply page with June programme info 

### ISSUE THREAD

**Issue by rebeccaradding** [foundersandcoders/our-site#389]
The Apply page needs to be updated to reflect the upcoming application windows for London and Nazareth.

From what I understand, the application window for London will be March 1 - 31. 

Will we be allowing more time for local students to apply for Nazareth, say March 1 - April 30? A lot depends on how much publicity our launch event generates (as well as interviews with @shiryz and @esraajb) and whether Coding for Everyone (likely beginning early February) engages a strong community in preparations.

**Comment by sofer** [comment]
Thanks for alerting. See #385

**Comment by sofer** [comment]
@rebeccaradding can we close this?

**Comment by rebeccaradding** [comment]
Yep!
