### ISSUE TITLE
Re-introduce the FAC FAQ

### ISSUE THREAD

**Issue by sofer** [foundersandcoders/our-site#391]
We used to have a FAQ (see https://github.com/foundersandcoders/our-site/blob/17b982d8c8948dc91f21d2b609c87dc69c272f5c/_harp/coders/faq/_faq.md).

Most of the information has migrated elsewhere on the site, but I wonder if we should look again at whether potential applicants have enough information.

@esraajb has pointed out that we could make it make a better case for why exactly potential applicants might want to take the course, what they can get out of it and where they can go next. One example he mentioned is the use of Cordova to build mobile apps and why that might be a better option than learning either Java or Swift or Objective-C.

**Comment by iteles** [comment]
Or rather, why we should use mobile PWAs instead of swift or objective-c for example ;)

**Comment by sofer** [comment]
Also true :-)

**Comment by rebeccaradding** [comment]
We have not re-introduced the FAQ, and it's been several months.
