### ISSUE TITLE
Application form indicates that applications are still open

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/our-site#392]
Someone posted in C4E gitter:
![fac-application-form](https://cloud.githubusercontent.com/assets/15656538/22438643/b2b5081e-e724-11e6-9598-47a8e116bf0b.png)
![fac-application-form2](https://cloud.githubusercontent.com/assets/15656538/22438646/b529182e-e724-11e6-8ad9-930c0f0e0f9d.png)

If applications are closed for both, we probably shouldn't even have the form available?

**Comment by sofer** [comment]
@jsms90 that's a mistake. It's closed now.
