### ISSUE TITLE
"Location" section

### ISSUE THREAD

**Issue by esraajb** [foundersandcoders/our-site#394]
Me and @rebeccaradding though it would be useful to have one more section on the website under the name "Location".
we will have London and Nazareth under this section with extended info about the specific location.

**Comment by rebeccaradding** [comment]
@esraajb how about **instead** of the `course info` button we have two buttons, one for London and one for Nazareth, with each linking to the README for now? That way the word `Nazareth` is on the front page.

Let's do this ASAP if possible.

**Comment by esraajb** [comment]
Can you please give me the link to the right reademes that i should link the button to ?

**Comment by rebeccaradding** [comment]
https://github.com/foundersandcoders/info/blob/master/nazareth.md

https://github.com/foundersandcoders/info/blob/master/london.md

**Comment by esraajb** [comment]
this nazareth readme is not updated thought.
ill link it, and ill open new issue regarding updating it.

**Comment by rebeccaradding** [comment]
@esraajb can you merge my PR's for the Nazareth README?

**Comment by rebeccaradding** [comment]
@Jbarget suggests that we replace the APPLY button on the picture with London and Nazareth buttons so that Nazareth appears in the first view.

**Comment by esraajb** [comment]
so instead of having Lon and Naz beside the Testimonials, replacing them with the apply button ?

**Comment by esraajb** [comment]
<img width="1412" alt="screen shot 2017-02-22 at 10 38 13 am" src="https://cloud.githubusercontent.com/assets/21229375/23203403/0bae295a-f8eb-11e6-9c85-264cf39a6537.png">

**Comment by rebeccaradding** [comment]
YES! But I'm not sure we need to raise the lightbulb so high...

**Comment by Jbarget** [comment]
👍  lovely

**Comment by esraajb** [comment]
<img width="1231" alt="screen shot 2017-02-22 at 10 45 32 am" src="https://cloud.githubusercontent.com/assets/21229375/23203670/2b6e8d60-f8ec-11e6-8511-539818e7360d.png">

**Comment by esraajb** [comment]
Nazareth button is under hover

**Comment by rebeccaradding** [comment]
Are you removing COURSE INFO from the bottom as to not be redundant?

**Comment by esraajb** [comment]
yes. we have only Testimonials on FAC9 pic

made a PR #395
