### ISSUE TITLE
Infographic for application process

### ISSUE THREAD

**Issue by rebeccaradding** [foundersandcoders/our-site#396]
At the Nazareth AGM, we discussed creating an infographic for the application process. @nogainbar @esraajb would it be possible to collaborate on this and get something ready for Monday, February 27?

**Comment by smarthutza** [comment]
@rebeccaradding @nogainbar @esraajb @jsms90 

I've addressed this issue. The infographic can be downloaded over here: https://www.dropbox.com/s/0qmlysprd4g7l4u/FAC%204.ai?dl=0

Let me know if you think it needs any amendments.

**Comment by rebeccaradding** [comment]
Application process is now MUCH easier to understand, thanks to @jsms90's reorganization. Closing issue for now.
