### ISSUE TITLE
FAC and Press

### ISSUE THREAD

**Issue by esraajb** [foundersandcoders/our-site#398]
I think with the opening of FAC Naz we had a lot of articles talking about us in the press.
let try to put them all in here and then ill make PR adding them to the website.

http://www.timesofisrael.com/nazareth-tech-scene-to-get-programmers-boost/
http://www.ukisraelhub.com/founders-coders-first-international-programme-launched-nazareth

**Comment by esraajb** [comment]
http://www.nazarethinfo.org/ar/events/%D8%A2%D8%AE%D8%B1-%D8%A7%D9%84%D8%AD%D8%AA%D9%84%D9%86%D8%A7%D8%AA/%D8%A8%D8%AD%D8%B6%D9%88%D8%B1-%D8%A7%D9%84%D8%B3%D9%81%D9%8A%D8%B1-%D8%A7%D9%84%D8%A8%D8%B1%D9%8A%D8%B7%D8%A7%D9%86%D9%8A-%D8%A7%D8%B7%D9%84%D8%A7%D9%82-%D9%85%D8%B4%D8%B1%D9%88%D8%B9-%D8%A7%D9%84%D8%A8%D8%B1%D9%85%D8%AC%D8%A9-%D8%A7%D9%84%D8%A3%D9%88%D9%84-%D9%85%D9%86-%D9%86%D9%88%D8%B9%D9%87-%D9%81%D9%8A-%D8%A7%D9%84%D9%86%D8%A7%D8%B5%D8%B1%D8%A9

**Comment by rebeccaradding** [comment]
Also, https://github.com/foundersandcoders/nazareth-programme/issues/95

**Comment by rebeccaradding** [comment]
First piece from Musawa: https://goo.gl/5nvP58

Second piece: https://tinyurl.com/m8rkvkf

**Comment by rebeccaradding** [comment]
Original JP piece: http://www.jpost.com/Business-and-Innovation/Tech/UK-based-NGO-brings-free-and-accessible-tech-training-to-Israeli-Arabs-in-Nazareth-474867

**Comment by rebeccaradding** [comment]
Bokra: http://www.bokra.net/Article-1361753#.WLP6p99AnNk.facebook
