### ISSUE TITLE
Inconsistent button colours on programme section

### ISSUE THREAD

**Issue by mattlub** [foundersandcoders/our-site#405]
![screen shot 2017-03-05 at 17 23 04](https://cloud.githubusercontent.com/assets/16781318/23588597/801f789e-01c8-11e7-9d4e-fd4f70254f8b.png)

**Comment by mattlub** [comment]
I noticed the same on programme information so maybe it's intentional. The issue was raised by @esraajb actually.

**Comment by Samatar26** [comment]
@mattlub  Apparently it's intentional, it makes sense for the apply button to kind of stick out.

**Comment by Samatar26** [comment]
@mattlub Can you close this issue if you feel that you've received an answer?
