### ISSUE TITLE
Landing page London/Nazareth links go to Github 

### ISSUE THREAD

**Issue by Suuuuha** [foundersandcoders/our-site#406]
the two links in the middle of the page, go to Github repos which is -in our opinion- bad UX. 
We propose very simple information pages for each, e.g at /programme/course-information/location

**Comment by mattlub** [comment]
I'm on it!

**Comment by rebeccaradding** [comment]
@mattlub @Suuuuha agreed! They were meant to be temporary until we were happy with the content. 

If you have any questions about the content, let me know. @edgarfinn @m4v15 have recently proposed an update to the Nazareth page: https://github.com/foundersandcoders/info/issues/6 but it has not been merged yet.
