### ISSUE TITLE
Email candidates their application

### ISSUE THREAD

**Issue by esraajb** [foundersandcoders/our-site#422]
I suggest we add this to the user-story of our website:
When you submit your application through google forms, you receive a copy of your application to your email.

Benefits: 
*applicants will spot mistakes in their application, and re-submit a corrected one if needed.
*not accepted applicant can revisit the application for improvements next time they apply.

**Comment by rebeccaradding** [comment]
@esraajb I have "edit after submit" selected - not sure how that works though. It should allow them to go back and revise if needed.

**Comment by emilyb7** [comment]
Just tested this (expect random response from me to the Naz application form) and it works fine. @esraajb can we close?
