### ISSUE TITLE
update "Our Story" text

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/our-site#428]
To reflect that the Nazareth campus has opened (and Gaza?)

**Comment by rebeccaradding** [comment]
I'm speaking with @saralk tomorrow so I'll check in about whether we are kosher to add this.

**Comment by rebeccaradding** [comment]
@jsms90 have written Ryan at GSG, will post an update when I receive a response.

**Comment by rebeccaradding** [comment]
GSG is not ready for us to share what we're going in Gaza. For now, have updated the copy to reflect only our activity in Nazareth.
