### ISSUE TITLE
incorrect link to London application google form

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/our-site#436]
This is still linked to the old version, where it says applications are closed :worried:

**Comment by rebeccaradding** [comment]
Oh no! Just checked, and the form was "not currently collecting responses." Have fixed it - give the link another try. If it works, please close 👍

**Comment by jsms90** [comment]
Cool. It's working :+1: 

But please let's not get into the habit of changing things without a PR. Pull requests are a valuable way of ensuring that multiple pairs of eyes are across any change that is made.

[We badly need a contributing guide](https://github.com/foundersandcoders/our-site/issues/414)

**Comment by rebeccaradding** [comment]
@jsms90 - sorry, didn't realize this was a change that would need a PR. I literally just flipped a switch on the Google form (which I did not realize had been turned off). Will do this differently next time!

**Comment by jsms90** [comment]
Oh right!! No, that doesn't need a PR!

Sorry, I clearly didn't know what was involved :sweat_smile:
