### ISSUE TITLE
include explanation of _why_ London is now offering a prep course

### ISSUE THREAD

**Issue by jsms90** [foundersandcoders/our-site#439]
London has been running for so long, that some people are bound to have seen the website before or heard of the course and wonder why we now offer a prep course when we didn't before.

Even if it is the first time someone has come to the website, the fact that we mention that our current process will be changing for the next cohort raises questions.

![image](https://user-images.githubusercontent.com/15656538/27480753-417a482c-5811-11e7-920d-06e4c7e32125.png)
![image](https://user-images.githubusercontent.com/15656538/27480811-98e6fd9e-5811-11e7-87fa-517c1c434075.png)
![image](https://user-images.githubusercontent.com/15656538/27480821-a65a35f4-5811-11e7-86df-89e0307c1280.png)

**Comment by rebeccaradding** [comment]
@jsms90 I like your answer, and I think it could form the basis of a short paragraph for the London APPLY page explaining the change.

**Comment by rebeccaradding** [comment]
Closing, as based on FAC12 applications and discussions with @sofer, London may not need a prep-course, and we have removed this info from the website. We can reevaluate in a couple of months and update accordingly.
