### ISSUE TITLE
inconsistency (and lack of clarity?) in London apply page

### ISSUE THREAD

**Issue by mattlub** [foundersandcoders/our-site#444]
Prompted by this gitter message which I wanted to reply to:

![screen shot 2017-06-27 at 15 12 17](https://user-images.githubusercontent.com/16781318/27591942-25a053ca-5b4b-11e7-92ea-ce3d1232a04f.png)

I went to https://foundersandcoders.com/apply/london and noticed it is inconsistent, stating:

> we do not expect you finish the course prerequisites before putting in your application. But you should make a sincere effort to start this work before we conduct interviews.

Followed soon after by:

>We will review applications and offer interviews at the end of July to all candidates who have completed the course prerequisites

One other thing, relating to the gitter message:
I don't know what people see now after they apply, but should there be a clearer message/email on what the next steps are, e.g. "now get started on the prerequesites, try to come to meetups, and stay in touch on the gitter channel!"? 

UPDATE: I just realised, maybe it means you are guaranteed an interview if you have done the prereqs, and you might get one if you haven't? So maybe it's not inconsistent, but it's definitely not clear. I would be happy to change it myself if someone clears up exactly what it's meant to say.

**Comment by eliascodes** [comment]
@mattlub thanks for spotting, probably worth cross-posting to [foundersandcoders/selection-committee](https://github.com/foundersandcoders/selection-committee).

@emilyb7 @nogainbar @sofer @sohilpandya ??

**Comment by emilyb7** [comment]
@mattlub @eliascodes thanks. I think that second sentence should be removed. @rebeccaradding do you agree?

**Comment by rebeccaradding** [comment]
You're all right - it's not completely clear. To be fair, we wanted to give ourselves some flexibility by promising to interview everyone who did complete the course prerequisites while not disqualifying people who didn't (so that we can offer a few interviews to people who seem less prepared but capable of preparing in time).

@mattlub @emilyb7 how would you make this more clear in the text?

**Comment by emilyb7** [comment]
Maybe add something one the end like "in exceptional circumstances, we may also offer interviews to candidates who have not fully completed the prerequisites. This will be at the selection panel's own discretion"... 

Maybe a bit friendlier than that though.

**Comment by mattlub** [comment]
"We will review applications and offer interviews at the end of July, including a guaranteed interview to all candidates who have completed the course prerequisites"

**Comment by rebeccaradding** [comment]
@mattlub that sounds good to me. Want to go ahead with a PR to change the copy?

**Comment by mattlub** [comment]
@rebeccaradding yep done.

**Comment by jsms90** [comment]
happy to close @mattlub ?
