### ISSUE TITLE
Add Yvonne to Our Team

### ISSUE THREAD

**Issue by yvonne-liu** [foundersandcoders/our-site#467]
😄

**Comment by yvonne-liu** [comment]
Suggested copy @iteles @rebeccaradding @sofer: 

_Yvonne Liu leads operations for Founders & Coders International. She is an advocate for growing communities, open-source systems, accessible education, and previously led operations in Asia for iFixit. A graduate of Founders & Coders London, she now divides her time between our UK and Middle East campuses._

**Comment by iteles** [comment]
Great copy @yvonne-liu !
