### ISSUE TITLE
Add Natalia and Mark under FCI Trustees

### ISSUE THREAD

**Issue by yvonne-liu** [foundersandcoders/our-site#469]
@beardfacebo @NataliaLKB 

Need a short bio (no more than 50 words) along with a square photo for the website please!

**Comment by NataliaLKB** [comment]
@yvonne-liu Here is my bio and image:

![img-20161007-wa0001 1](https://user-images.githubusercontent.com/8774970/34160051-534e093c-e4c3-11e7-9ac0-1dc1b4ed431d.jpg)

> Natalia Baltazar is a Developer Manager at the Guardian and a graduate of Founders and Coders. She is passionate about providing a free and accessible way for people to learn software development and believes in the Founders and Coders mission.

Let me know if you want more or less than this :)

**Comment by yvonne-liu** [comment]
Closing because trustees will added to www.foundersandcoders.org instead.
