### ISSUE TITLE
Update Nelson's bio

### ISSUE THREAD

**Issue by yvonne-liu** [foundersandcoders/our-site#481]
If no updates necessary/desired, please close issue @nelsonic.

**Comment by nelsonic** [comment]
@yvonne-liu are you referring to this page:
https://github.com/foundersandcoders/our-site/blob/6249db969806fd44930051e105b028e53e40ebc3/_harp/community/_team.md#L30 ?

**Comment by yvonne-liu** [comment]
Yes, thanks for clarifying!

**Comment by nelsonic** [comment]
I'm happy to leave as-is for now. 
If more detail is required, please link to: https://www.linkedin.com/in/nelsonic

**Comment by iteles** [comment]
dwyl.com maybe 😉
