### ISSUE TITLE
Add clarity to Codewars before next application opens 

### ISSUE THREAD

**Issue by yvonne-liu** [foundersandcoders/our-site#495]
It seems Codewars changed their rule on how many honor points you need before you can publish a kata (it's caused some confusion during FAC14 application). Before FAC15 application opens, we should update the copy on the website: 

Currently: 
> Reach 5 kyu in JavaScript on Codewars
Create at least one JavaScript kata

Suggested copy: 
> Reach 5 kyu and 300 honor points in JavaScript on Codewars
Create at least one JavaScript kata 

> Before creating your kata, check out these tips from Codewars on [creating your first kata](https://github.com/Codewars/codewars.com/wiki/Tutorial%3A-Create-Your-First-Kata) and [kata best practices](https://github.com/Codewars/codewars.com/wiki/Kata-Best-Practices). 

> Be mindful that Codewars can be quite strict on the quality of their published katas, so katas not up to the community standard may be retired or stuck in beta. 

I'm unsure on the last sentence, but I would like to give applicants a bit of a heads up on the possible hostility from the Codewars community with low quality katas.

**Comment by ZooeyMiller** [comment]
I don't see so much how creating a kata contributes to our understanding of a students capabilities. 

Sometimes in testing week I've seen confusion from it even - 'What about random tests?'

I guess you can't _really_ cheat on making a kata, where you kind of can in getting to 5 kyu and such, but  I don't know how much of an issue that's been in the past.
