### ISSUE TITLE
We need a beautiful image for the landing page

### ISSUE THREAD

**Issue by izaakrogan** [foundersandcoders/our-site#6]

**Comment by nelsonic** [comment]
Wish you had been there yesterday for #GardenLunch ...
The group photo we took *would* have been great if you had been in it... 
We should try and be not organised and get MOAR people to come next lunch so we can have *way* MOAR lovely faces!
A good team photo on the homepage is always going to say "people first".

**Comment by izaakrogan** [comment]
Great photos!

**Comment by besarthoxhaj** [comment]
@izaakrogan @nelsonic what about a series of many blocks with images? I saw a couple of websites in the past and that impressed me.

**Comment by iteles** [comment]
Could we temporarily use [one of the photos from the garden lunch](https://plus.google.com/photos/105022275514300144972/albums/6149120837482523937/6149153485675817154?pid=6149153485675817154&oid=105022275514300144972&authkey=CMyvrP6poZW-uwE)? I see no problem with updating this image regularly.

**Comment by rebeccaradding** [comment]
We now have a landing page photo, closing issue.
